name: Publish Package to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
      - name: Check Package Version
        run: |
          version=$(uv version --short)
          tag=${GITHUB_REF#refs/tags/}
          tag=${tag#v}
          if [[ "${tag}" != "${version}" ]]; then
            echo "Error: Package version ${version} does not match repository tag ${tag}"
            exit 1
          fi
      - run: uv python install 3.11
      - run: uv build --python 3.11
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          password: ${{ secrets.PYPI_TOKEN }}
